---
host: https://markkarpov.com/ # the trailing slash is important right now
main_menu:
  - title: Posts
    link: "/posts.html"
  - title: Notes
    link: "/notes.html"
  - title: Learn Haskell
    link: "/learn-haskell.html"
  - title: OSS
    link: "/oss.html"
  - title: Resume
    link: "/resume.html"
  - title: About
    link: "/about.html"
external_posts:
  - published: May 27, 2019
    title:     "Ormolu: format Haskell code like never before"
    url:       https://www.tweag.io/posts/2019-05-27-ormolu.html
  - published: February 13, 2019
    title:     The types got you
    url:       https://www.tweag.io/posts/2019-02-13-types-got-you.html
  - published: April 17, 2018
    title:     Stackage HEAD is now live!
    url:       https://www.tweag.io/posts/2018-04-17-stackage-head-is-live.html
  - published: February 28, 2018
    title:     Bazel now supports building Haskell
    url:       https://www.tweag.io/posts/2018-02-28-bazel-haskell.html
  - published: March 29, 2017
    title:     "Hapistrano's new features"
    url:       https://www.stackbuilders.com/news/hapistrano-s-new-features
  - published: August 2, 2016
    title:     Concurrent Haskell in the real world
    url:       https://www.stackbuilders.com/news/concurrent-haskell-in-the-real-world
  - published: June 29, 2016
    title:     Cassava Megaparsec library released
    url:       https://www.stackbuilders.com/news/cassava-megaparsec-library-released
external_tutorials:
  - published: February 1, 2017
    title:     GHC generics explained
    url:       https://www.stackbuilders.com/tutorials/haskell/generics/
  - published: November 29, 2016
    title:     GHC optimization and fusion
    url:       https://www.stackbuilders.com/tutorials/haskell/ghc-optimization-and-fusion/
  - published: September 21, 2016
    title:     Servant authentication and sessions via cookies
    url:       https://www.stackbuilders.com/tutorials/haskell/servant-auth/
  - published: August 17, 2016
    title:     Mustache templates in Haskell
    url:       https://www.stackbuilders.com/tutorials/haskell/mustache-templates/
  - published: June 22, 2016
    title:     Creating a GUI application in Haskell
    url:       https://www.stackbuilders.com/tutorials/haskell/gui-application/
  - published: June 7, 2016
    title:     Image processing with Juicy Pixels and Repa
    url:       https://www.stackbuilders.com/tutorials/haskell/image-processing/
recommended_tutorials:
  - topic: Data formats
    title: "Aeson: the tutorial"
    url:   https://artyom.me/aeson
  - topic: Concurrency
    title: Async library
    url:   https://haskell-lang.org/library/async
  - topic: Streaming
    title: Conduit library
    url:   https://haskell-lang.org/library/conduit
  - topic: Data structures
    title: Vector library
    url:   https://haskell-lang.org/library/vector
  - topic: Command line options
    title: Optparse applicative tutorial
    url:   https://github.com/pcapriotti/optparse-applicative/blob/master/README.md
  - topic: Configuration files
    title: Dhall tutorial
    url:   https://hackage.haskell.org/package/dhall/docs/Dhall-Tutorial.html
  - topic: More precise typing
    title: Liquid Haskell tutorial
    url:   https://liquid.kosmikus.org
  - topic: Generics
    title: Applying type-level and generic programming in Haskell
    url:   https://github.com/kosmikus/SSGEP
  - topic: Type-level programming
    title: Haskell's kind system - a primer
    url:   https://diogocastro.com/blog/2018/10/17/haskells-kind-system-a-primer/
  - topic: Dependent types
    title: Introduction to singletons
    url:   https://blog.jle.im/entries/series/+introduction-to-singletons.html
social:
  email:         mailto:markkarpov92@gmail.com
  github:        https://github.com/mrkkrp
  twitter:       https://twitter.com/mrkkrp
  reddit:        https://www.reddit.com/user/mrkkrp
  linkedin:      https://www.linkedin.com/in/mark-karpov-73789914a
  stackoverflow: https://stackoverflow.com/users/3687048/mark
  instagram:     https://www.instagram.com/mrkkrp/
oss:
  - section: Haskell
    items:
      - repo: mrkkrp/megaparsec
        name: Megaparsec
        desc: Industrial-strength monadic parser combinator library
      - repo: tweag/ormolu
        name: Ormolu
        desc: A formatter for Haskell source code
      - repo: mrkkrp/req
        name: Req
        desc: Easy-to-use, type-safe, expandable, high-level HTTP library
      - repo: mrkkrp/zip
        name: Zip
        desc: Efficient library for manipulating zip archives
      - repo: mrkkrp/modern-uri
        name: Modern URI
        desc: Modern library for working with URIs
      - repo: mrkkrp/text-metrics
        name: Text metrics
        desc: Calculate various string metrics efficiently in Haskell
      - repo: stackbuilders/stache
        name: Stache
        desc: Mustache templates for Haskell
      - repo: commercialhaskell/path
        name: Path
        desc: Support for well-typed paths
      - repo: mrkkrp/path-io
        name: Path IO
        desc: Operations on files and directories with well-typed paths
      - repo: mrkkrp/flac
        name: FLAC
        desc: Complete high-level Haskell binding to libFLAC
      - repo: mrkkrp/parser-combinators
        name: Parser combinators
        desc: Lightweight package providing commonly useful parser combinators
      - repo: mrkkrp/hspec-megaparsec
        name: Hspec Megaparsec
        desc: Utility functions for testing Megaparsec parsers with Hspec
      - repo: mrkkrp/ghc-syntax-highlighter
        name: GHC syntax highlighter
        desc: Correct syntax highlighter for Haskell using GHC itself
      - repo: mrkkrp/forma
        name: Forma
        desc: Parse and validate forms in JSON format
      - repo: mrkkrp/identicon
        name: Identicon
        desc: Flexible generation of identicons in Haskell
      - repo: mrkkrp/htaglib
        name: HTagLib
        desc: Haskell bindings for TagLib, an audio meta-data library
      - repo: mrkkrp/wave
        name: WAVE
        desc: Work with WAVE and RF64 files in Haskell
      - repo: mrkkrp/lame
        name: LAME
        desc: Fairly complete high-level Haskell binding to LAME encoder
      - repo: mrkkrp/JuicyPixels-extra
        name: Juicy Pixels extra
        desc: Efficiently scale, crop, flip images with JuicyPixels
      - repo: mrkkrp/pagination
        name: Pagination
        desc: Framework-agnostic pagination boilerplate
      - repo: mrkkrp/req-conduit
        name: Req conduit
        desc: Conduit utilities that work with Req
      - repo: mrkkrp/flac-picture
        name: FLAC picture
        desc: Support for writing picture to FLAC metadata blocks with JuicyPixels
      - repo: mrkkrp/cue-sheet
        name: CUE Sheet
        desc: Support for construction, rendering, and parsing of CUE sheets
      - repo: mrkkrp/html-entity-map
        name: HTML entity map
        desc: Map from HTML5 entity names to the corresponding Unicode text
      - repo: mrkkrp/tagged-identity
        name: Tagged identity
        desc: Trivial monad transformer that allows identical monad stacks have different types
  - section: MMark
    items:
      - repo: mmark-md/mmark
        name: MMark
        desc: Strict markdown processor for writers
      - repo: mmark-md/mmark-cli
        name: MMark CLI
        desc: Command line interface to the MMark markdown processor
      - repo: mmark-md/mmark-ext
        name: MMark extensions
        desc: Commonly useful extensions for the MMark markdown processor
      - repo: mmark-md/flycheck-mmark
        name: Flycheck support for MMark
        desc: Flycheck checker for the MMark markdown processor
  - section: Emacs Lisp
    items:
      - repo: mrkkrp/vimish-fold
        name: Vimish fold
        desc: Vim-like text folding for Emacs
      - repo: mrkkrp/modalka
        name: Modalka
        desc: Easily introduce native modal editing of your own design
      - repo: mrkkrp/typit
        name: Typit
        desc: Typing game for Emacs similar to the tests on 10 fast fingers
      - repo: mrkkrp/ace-popup-menu
        name: Ace popup menu
        desc: Replace GUI popup menu in Emacs with something more efficient
      - repo: mrkkrp/fix-word
        name: Fix word
        desc: Transform words in Emacs (upcase, downcase, capitalize, etc.)
      - repo: mrkkrp/cyphejor
        name: Cyphejor
        desc: Shorten major mode names using user-defined rules
      - repo: mrkkrp/kill-or-bury-alive
        name: Kill or bury alive
        desc: Precise control over buffer killing in Emacs
      - repo: mrkkrp/char-menu
        name: Char menu
        desc: Create your own menu for fast insertion of arbitrary symbols
      - repo: mrkkrp/zzz-to-char
        name: Zzz to char
        desc: Fancy replacement for zap-to-char in Emacs
      - repo: mrkkrp/mmt
        name: MMT
        desc: Missing macro tools for Emacs Lisp
      - repo: mrkkrp/avy-menu
        name: Avy menu
        desc: Library providing avy-powered popup menu for Emacs
      - repo: mrkkrp/fix-input
        name: Fix input
        desc: Make input methods play nicely with alternative keyboard layout
  - section: Hasky Mode
    items:
      - repo: hasky-mode/hasky-stack
        name: Hasky Stack
        desc: Interface to the Stack Haskell development tool
      - repo: hasky-mode/hasky-extensions
        name: Hasky extensions
        desc: Toggle Haskell language extensions from Emacs
  - section: Other
    items:
      - repo: tweag/rules_haskell
        name: Rules Haskell
        desc: Rules for building Haskell code using Bazel

copyright: "© 2015–2019 Mark Karpov"
feed:
  author_name:  Mark Karpov
  author_email: markkarpov92@gmail.com
