---
host: https://markkarpov.com/ # the trailing slash is important right now
main_menu:
  - title: Posts
    link: "/posts.html"
  - title: Learn Haskell
    link: "/learn-haskell.html"
  - title: OSS
    link: "/oss.html"
  - title: About
    link: "/about.html"
tutorials_for_former_employers:
  - published: February 1, 2017
    title:     GHC generics explained
    url:       https://www.stackbuilders.com/tutorials/haskell/generics/
  - published: November 29, 2016
    title:     GHC optimization and fusion
    url:       https://www.stackbuilders.com/tutorials/haskell/ghc-optimization-and-fusion/
  - published: September 21, 2016
    title:     Servant authentication and sessions via cookies
    url:       https://www.stackbuilders.com/tutorials/haskell/servant-auth/
  - published: August 17, 2016
    title:     Mustache templates in Haskell
    url:       https://www.stackbuilders.com/tutorials/haskell/mustache-templates/
  - published: June 22, 2016
    title:     Creating a GUI application in Haskell
    url:       https://www.stackbuilders.com/tutorials/haskell/gui-application/
  - published: June 7, 2016
    title:     Image processing with Juicy Pixels and Repa
    url:       https://www.stackbuilders.com/tutorials/haskell/image-processing/
social:
  email:         markkarpov92@gmail.com
  github:        https://github.com/mrkkrp
  twitter:       https://twitter.com/mrkkrp
  reddit:        https://www.reddit.com/user/mrkkrp
  stackoverflow: https://stackoverflow.com/users/3687048/mark
  instagram:     https://www.instagram.com/mrkkrp/
oss:
  - section: Haskell
    items:
      - repo: mrkkrp/megaparsec
        name: Megaparsec
        desc: Industrial-strength monadic parser combinator library
      - repo: mrkkrp/req
        name: Req
        desc: Easy-to-use, type-safe, expandable, high-level HTTP library
      - repo: mrkkrp/zip
        name: Zip
        desc: Efficient library for manipulating zip archives
      - repo: commercialhaskell/path
        name: Path
        desc: Support for well-typed paths
      - repo: mrkkrp/path-io
        name: Path IO
        desc: Operations on files and directories with well-typed paths
      - repo: stackbuilders/stache
        name: Stache
        desc: Mustache templates for Haskell
      - repo: mrkkrp/text-metrics
        name: Text Metrics
        desc: Calculate various string metrics efficiently in Haskell
      - repo: mrkkrp/flac
        name: FLAC
        desc: Complete high-level Haskell binding to libFLAC
      - repo: mrkkrp/identicon
        name: Identicon
        desc: Flexible generation of identicons in Haskell
      - repo: mrkkrp/parser-combinators
        name: Parser combinators
        desc: Lightweight package providing commonly useful parser combinators
      - repo: mrkkrp/hspec-megaparsec
        name: Hspec Megaparsec
        desc: Utility functions for testing Megaparsec parsers with Hspec
      - repo: mrkkrp/htaglib
        name: HTagLib
        desc: Haskell bindings for TagLib, an audio meta-data library
      - repo: mrkkrp/plan-b
        name: Plan B
        desc: Failure-tolerant file and directory editing for Haskell
      - repo: mrkkrp/slug
        name: Slug
        desc: Type-safe slugs for Yesod ecosystem
      - repo: mrkkrp/pagination
        name: Pagination
        desc: Framework-agnostic pagination boilerplate
      - repo: mrkkrp/JuicyPixels-extra
        name: Juicy Pixels Extra
        desc: Efficiently scale, crop, flip images with JuicyPixels
      - repo: mrkkrp/flac-picture
        name: FLAC picture
        desc: Support for writing picture to FLAC metadata blocks with JuicyPixels
      - repo: mrkkrp/forma
        name: Forma
        desc: Parse and validate forms in JSON format
      - repo: mrkkrp/tagged-identity
        name: Tagged Identity
        desc: Trivial monad transformer that allows identical monad stacks have different types
      - repo: mrkkrp/lame
        name: LAME
        desc: Fairly complete high-level Haskell binding to LAME encoder
      - repo: mrkkrp/wave
        name: WAVE
        desc: Work with WAVE and RF64 files in Haskell
      - repo: mrkkrp/data-check
        name: Data Check
        desc: Library for checking and normalization of data (e.g. from web forms)
      - repo: mrkkrp/cue-sheet
        name: CUE Sheet
        desc: Support for construction, rendering, and parsing of CUE sheets
  - section: Emacs Lisp
    items:
      - repo: mrkkrp/vimish-fold
        name: Vimish Fold
        desc: Vim-like text folding for Emacs
      - repo: mrkkrp/modalka
        name: Modalka
        desc: Easily introduce native modal editing of your own design
      - repo: mrkkrp/typit
        name: Typit
        desc: Typing game for Emacs similar to the tests on 10 fast fingers
      - repo: mrkkrp/ace-popup-menu
        name: Ace Popup Menu
        desc: Replace GUI popup menu in Emacs with something more efficient
      - repo: mrkkrp/fix-word
        name: Fix Word
        desc: Transform words in Emacs (upcase, downcase, capitalize, etc.)
      - repo: hasky-mode/hasky-stack
        name: Hasky Stack
        desc: Interface to the Stack Haskell development tool
      - repo: mrkkrp/cyphejor
        name: Cyphejor
        desc: Shorten major mode names using user-defined rules
      - repo: mrkkrp/kill-or-bury-alive
        name: Kill or Bury Alive
        desc: Precise control over buffer killing in Emacs
      - repo: mrkkrp/char-menu
        name: Char menu
        desc: Create your own menu for fast insertion of arbitrary symbols
      - repo: mrkkrp/zzz-to-char
        name: Zzz to char
        desc: Fancy replacement for zap-to-char in Emacs
      - repo: hasky-mode/hasky-extensions
        name: Hasky Extensions
        desc: Toggle Haskell language extensions from Emacs
      - repo: mrkkrp/mmt
        name: MMT
        desc: Missing macro tools for Emacs Lisp
      - repo: mrkkrp/avy-menu
        name: Avy Menu
        desc: Library providing avy-powered popup menu for Emacs
      - repo: mrkkrp/fix-input
        name: Fix Input
        desc: Make input methods play nicely with alternative keyboard layout
  - section: Common Lisp
    items:
      - repo: mrkkrp/unix-opts
        name: Unix opts
        desc: Unix-style command line options parser
      - repo: mrkkrp/mk-string-metrics
        name: MK string metrics
        desc: Calculate various string metrics efficiently in Common Lisp
      - repo: mrkkrp/cl-readline
        name: CL Readline
        desc: Common Lisp bindings to GNU Readline library
      - repo: mrkkrp/cl-ansi-term
        name: CL ANSI term
        desc: Colorized output on ANSI terminals and more
      - repo: mrkkrp/trivial-update
        name: Trivial update
        desc: Easy modification of places with any given function
copyright: "© 2015–2017 Mark Karpov"
feed:
  author_name:  Mark Karpov
  author_email: markkarpov92@gmail.com
